version: '3.8'

services:
  bone-cancer-api:
    build: .
    container_name: bone-cancer-api
    ports:
      - "8006:8006"
    environment:
      - MODEL_PATH=model/bone_cancer_model.pth
      - IMG_SIZE=224
      - MC_PASSES=10
    volumes:
      - ./model:/app/model
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - bone-cancer-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-bone-cancer
    command: http bone-cancer-api:8006
    environment:
      - NGROK_AUTHTOKEN=3CYCoqthKel97RPqhohZDn5YmSm_2ju6X8WUTWKXnuLnvbvku
    ports:
      - "4040:4040"
    depends_on:
      - bone-cancer-api
    networks:
      - bone-cancer-network

networks:
  bone-cancer-network:
    driver: bridge