apiVersion: v1
kind: Service
metadata:
  name: bone-cancer-service
  labels:
    app: bone-cancer
spec:
  selector:
    app: bone-cancer
  type: NodePort
  ports:
  - port: 8006
    targetPort: 8006
    nodePort: 32131
    protocol: TCP
    name: http